version: 1
build:
  steps:
    - name: Install dependencies
      cmd: npm install
    - name: Build
      cmd: npm run build
    - name: Export
      cmd: npm run export
  environment:
    NODE_VERSION: 16
  outputDir: out
  artifactType: static-site
routes:
  - src: /api/(.*)
    dest: https://your-app-name.onrender.com/api/$1
  - src: /(.*)\.(png|jpg|jpeg|gif|svg|ico)
    headers:
      cache-control: public, max-age=31536000, immutable
    dest: /out/$1.$2
  - src: /(.*)\.(js|css|html|json)
    headers:
      cache-control: public, max-age=31536000, immutable
    dest: /out/$1.$2
  - src: /.*
    headers:
      cache-control: public, max-age=0, must-revalidate
    dest: /out/index.html
